/*
 *   Copyright 2012 Hai Bison
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package group.pals.android.lib.ui.filechooser.io.localfile;

import group.pals.android.lib.ui.filechooser.io.IFile;
import group.pals.android.lib.ui.filechooser.utils.MimeTypes;
import group.pals.android.lib.ui.filechooser.utils.history.History;

import java.io.File;
import java.util.List;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Build;
import android.os.Parcel;
import android.os.Parcelable;
import android.provider.MediaStore;

/**
 * This is a wrapper for {@link File}.
 * 
 * @author Hai Bison
 * @since v3.2
 */
public class LocalFile extends File implements IFile {

    /**
     * Auto-generated by Eclipse.
     */
    private static final long serialVersionUID = 2068049445895497580L;

    public LocalFile(String pathname) {
        super(pathname);
    }// LocalFile()

    public LocalFile(File file) {
        this(file.getAbsolutePath());
    }// LocalFile()

    @Override
    public IFile parentFile() {
        return getParent() == null ? null : new LocalFile(getParent());
    }// parentFile()

    /**
     * By default, {@link File} compares to another one by its pathname. So if
     * two different {@link File}'s have same pathname, they are equal. But to
     * let the {@link History} works, we don't do that.<br>
     * For example we have this history: 1-2-3-2-4-5, and it is used in a
     * {@link List}, then if we use {@link File}, we will only get {@code 1} for
     * method {@link List#indexOf(Object)} with file "2". But we have 2
     * positions for "2".<br>
     * <br>
     * So, we override this method :-) The result is a comparison of operator
     * {@code ==}
     */
    @Override
    public boolean equals(Object obj) {
        return this == obj;
    }

    @Override
    public boolean equalsToPath(IFile file) {
        return file == null ? false : getAbsolutePath().equals(file.getAbsolutePath());
    }// equalsToPath()

    @Override
    public IFile clone() {
        return new LocalFile(getAbsolutePath());
    }

    /**
     * <b>Note:</b> If this file can be generated a thumbnail, its dimension
     * will be not precise as input {@code width}/ {@code height}. You must take
     * care of the UI.
     */
    @Override
    public Bitmap genThumbnail(int width, int height) {
        if (isDirectory() || width <= 0 || height <= 0)
            return null;

        if (getName().matches(MimeTypes._RegexFileTypeImages)) {
            BitmapFactory.Options options = new BitmapFactory.Options();

            // first, get the size
            options.inJustDecodeBounds = true;
            BitmapFactory.decodeFile(getAbsolutePath(), options);

            if (options.outHeight < 0 || options.outWidth < 0)
                return null;

            if (options.outWidth == 0 || options.outHeight == 0)
                return Bitmap.createBitmap(0, 0, Bitmap.Config.ALPHA_8);

            // calculate the scale
            boolean isWider = options.outWidth >= options.outHeight;
            int scale = isWider ? options.outWidth / width : options.outHeight / height;
            // round the scale to power of 2
            scale = (int) Math.round(Math.pow(2, Math.log(scale) / Math.log(2)));

            options.inJustDecodeBounds = false;
            options.inSampleSize = scale;
            return BitmapFactory.decodeFile(getAbsolutePath(), options);
        }// thumbnail for image files
        else if (getName().matches(MimeTypes._RegexFileTypeVideos)) {
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.FROYO)
                return null;
            return ThumbnailUtilsCompat.createVideoThumbnail(getAbsolutePath(), MediaStore.Images.Thumbnails.MINI_KIND);
        }// thumbnail for video files

        return null;
    }// genThumbnail()

    /*-----------------------------------------------------
     * Parcelable
     */

    @Override
    public int describeContents() {
        // TODO Auto-generated method stub
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(getAbsolutePath());
    }

    public static final Parcelable.Creator<LocalFile> CREATOR = new Parcelable.Creator<LocalFile>() {

        public LocalFile createFromParcel(Parcel in) {
            return new LocalFile(in);
        }

        public LocalFile[] newArray(int size) {
            return new LocalFile[size];
        }
    };

    private LocalFile(Parcel in) {
        this(in.readString());
    }
}
